### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by oscar20200122** [manateelazycat/key-echo#6]
pip3 install epc sexpdata six libinput libevdev

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: epc in ./.local/lib/python3.11/site-packages (0.0.5)
Requirement already satisfied: sexpdata in ./.local/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: six in ./.local/lib/python3.11/site-packages (1.16.0)
ERROR: Could not find a version that satisfies the requirement libinput (from versions: none)
ERROR: No matching distribution found for libinput

**Comment by manateelazycat** [comment]
@mumu-lhl Can you help to review this?

**Comment by mumu-lhl** [comment]
把 libinput 换成 python-libinput
